import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Achievement from '#models/achievement'

export default class extends BaseSeeder {
  async run() {
    const achievements = [
      {
        key: 'streak_3',
        category: 'streak' as const,
        title: 'Первые шаги',
        description: 'Тренируйтесь 3 дня подряд',
        icon: '🔥',
        color: 'orange',
        requirementType: 'streak_days',
        requirementValue: 3,
        isActive: true,
      },
      {
        key: 'streak_7',
        category: 'streak' as const,
        title: 'Неделя силы',
        description: 'Тренируйтесь 7 дней подряд',
        icon: '💪',
        color: 'emerald',
        requirementType: 'streak_days',
        requirementValue: 7,
        isActive: true,
      },
      {
        key: 'streak_14',
        category: 'streak' as const,
        title: 'Две недели без остановки',
        description: 'Тренируйтесь 14 дней подряд',
        icon: '🎯',
        color: 'blue',
        requirementType: 'streak_days',
        requirementValue: 14,
        isActive: true,
      },
      {
        key: 'streak_30',
        category: 'streak' as const,
        title: 'Месяц дисциплины',
        description: 'Тренируйтесь 30 дней подряд',
        icon: '🏆',
        color: 'yellow',
        requirementType: 'streak_days',
        requirementValue: 30,
        isActive: true,
      },
      {
        key: 'streak_60',
        category: 'streak' as const,
        title: 'Два месяца упорства',
        description: 'Тренируйтесь 60 дней подряд',
        icon: '👑',
        color: 'purple',
        requirementType: 'streak_days',
        requirementValue: 60,
        isActive: true,
      },
      {
        key: 'streak_100',
        category: 'streak' as const,
        title: 'Сотня',
        description: 'Тренируйтесь 100 дней подряд',
        icon: '💯',
        color: 'pink',
        requirementType: 'streak_days',
        requirementValue: 100,
        isActive: true,
      },
      {
        key: 'streak_365',
        category: 'streak' as const,
        title: 'Год без перерыва',
        description: 'Тренируйтесь 365 дней подряд',
        icon: '🌟',
        color: 'gold',
        requirementType: 'streak_days',
        requirementValue: 365,
        isActive: true,
      },
      // Всего тренировок
      {
        key: 'workouts_1',
        category: 'workout' as const,
        title: 'Первая тренировка',
        description: 'Завершите первую тренировку',
        icon: '🎉',
        color: 'emerald',
        requirementType: 'total_workouts',
        requirementValue: 1,
        isActive: true,
      },
      {
        key: 'workouts_10',
        category: 'workout' as const,
        title: 'Десятка',
        description: 'Завершите 10 тренировок',
        icon: '💪',
        color: 'blue',
        requirementType: 'total_workouts',
        requirementValue: 10,
        isActive: true,
      },
      {
        key: 'workouts_50',
        category: 'workout' as const,
        title: 'Полтинник',
        description: 'Завершите 50 тренировок',
        icon: '🔥',
        color: 'orange',
        requirementType: 'total_workouts',
        requirementValue: 50,
        isActive: true,
      },
      {
        key: 'workouts_100',
        category: 'workout' as const,
        title: 'Сотня тренировок',
        description: 'Завершите 100 тренировок',
        icon: '🏅',
        color: 'yellow',
        requirementType: 'total_workouts',
        requirementValue: 100,
        isActive: true,
      },
      {
        key: 'workouts_500',
        category: 'workout' as const,
        title: 'Легенда',
        description: 'Завершите 500 тренировок',
        icon: '👑',
        color: 'purple',
        requirementType: 'total_workouts',
        requirementValue: 500,
        isActive: true,
      },
      // Использование функционала
      {
        key: 'first_ai_chat',
        category: 'usage' as const,
        title: 'Первый диалог с ИИ',
        description: 'Отправьте первое сообщение AI-помощнику',
        icon: '🤖',
        color: 'emerald',
        requirementType: 'ai_chat_messages',
        requirementValue: 1,
        isActive: true,
      },
      {
        key: 'ai_chats_10',
        category: 'usage' as const,
        title: 'AI Собеседник',
        description: 'Отправьте 10 сообщений AI-помощнику',
        icon: '💬',
        color: 'blue',
        requirementType: 'ai_chat_messages',
        requirementValue: 10,
        isActive: true,
      },
      {
        key: 'ai_chats_50',
        category: 'usage' as const,
        title: 'AI Эксперт',
        description: 'Отправьте 50 сообщений AI-помощнику',
        icon: '🧠',
        color: 'purple',
        requirementType: 'ai_chat_messages',
        requirementValue: 50,
        isActive: true,
      },
      // Социальные
      {
        key: 'find_trainer',
        category: 'social' as const,
        title: 'Найди своего тренера',
        description: 'Присоединитесь к персональному тренеру',
        icon: '🤝',
        color: 'emerald',
        requirementType: 'trainers_connected',
        requirementValue: 1,
        isActive: true,
      },
      {
        key: 'first_group_join',
        category: 'social' as const,
        title: 'В команде!',
        description: 'Вступите в первую группу тренера',
        icon: '👥',
        color: 'cyan',
        requirementType: 'groups_joined',
        requirementValue: 1,
        isActive: true,
      },
      {
        key: 'first_trainer_message',
        category: 'social' as const,
        title: 'Первый контакт',
        description: 'Напишите сообщение тренеру впервые',
        icon: '📩',
        color: 'indigo',
        requirementType: 'trainer_messages',
        requirementValue: 1,
        isActive: true,
      },
      {
        key: 'trainer_messages_50',
        category: 'social' as const,
        title: 'Активный общник',
        description: 'Отправьте 50 сообщений тренеру',
        icon: '🗣️',
        color: 'pink',
        requirementType: 'trainer_messages',
        requirementValue: 50,
        isActive: true,
      },
    ]

    await Achievement.updateOrCreateMany('key', achievements)
  }
}
