import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Achievement from '#models/achievement'

export default class extends BaseSeeder {
  async run() {
    // Удаляем старые streak-ачивки с day-based ключами
    await Achievement.query()
      .whereIn('key', [
        'streak_3',
        'streak_7',
        'streak_14',
        'streak_30',
        'streak_60',
        'streak_100',
        'streak_365',
      ])
      .delete()

    const achievements = [
      {
        key: 'streak_1w',
        category: 'streak' as const,
        title: 'Первая неделя',
        description: 'Завершите 1 неделю ударного режима',
        icon: '🔥',
        color: 'orange',
        requirementType: 'streak_days',
        requirementValue: 1,
        isActive: true,
      },
      {
        key: 'streak_2w',
        category: 'streak' as const,
        title: 'Две недели подряд',
        description: 'Завершите 2 недели ударного режима',
        icon: '💪',
        color: 'emerald',
        requirementType: 'streak_days',
        requirementValue: 2,
        isActive: true,
      },
      {
        key: 'streak_4w',
        category: 'streak' as const,
        title: 'Месяц дисциплины',
        description: 'Завершите 4 недели ударного режима',
        icon: '🎯',
        color: 'blue',
        requirementType: 'streak_days',
        requirementValue: 4,
        isActive: true,
      },
      {
        key: 'streak_8w',
        category: 'streak' as const,
        title: 'Два месяца упорства',
        description: 'Завершите 8 недель ударного режима',
        icon: '🏆',
        color: 'yellow',
        requirementType: 'streak_days',
        requirementValue: 8,
        isActive: true,
      },
      {
        key: 'streak_16w',
        category: 'streak' as const,
        title: 'Четыре месяца',
        description: 'Завершите 16 недель ударного режима',
        icon: '👑',
        color: 'purple',
        requirementType: 'streak_days',
        requirementValue: 16,
        isActive: true,
      },
      {
        key: 'streak_26w',
        category: 'streak' as const,
        title: 'Полгода в деле',
        description: 'Завершите 26 недель ударного режима',
        icon: '💯',
        color: 'pink',
        requirementType: 'streak_days',
        requirementValue: 26,
        isActive: true,
      },
      {
        key: 'streak_52w',
        category: 'streak' as const,
        title: 'Год без остановки',
        description: 'Завершите 52 недели ударного режима',
        icon: '🌟',
        color: 'gold',
        requirementType: 'streak_days',
        requirementValue: 52,
        isActive: true,
      },
      {
        key: 'streak_52w_intensive',
        category: 'streak' as const,
        title: 'Элита',
        description: 'Завершите 52 недели в усиленном режиме (5 тренировок в неделю)',
        icon: '⚡',
        color: 'purple',
        requirementType: 'streak_intensive_weeks',
        requirementValue: 52,
        isActive: true,
      },
      // Всего тренировок
      {
        key: 'workouts_1',
        category: 'workout' as const,
        title: 'Первая тренировка',
        description: 'Завершите первую тренировку',
        icon: '🎉',
        color: 'emerald',
        requirementType: 'total_workouts',
        requirementValue: 1,
        isActive: true,
      },
      {
        key: 'workouts_10',
        category: 'workout' as const,
        title: 'Десятка',
        description: 'Завершите 10 тренировок',
        icon: '💪',
        color: 'blue',
        requirementType: 'total_workouts',
        requirementValue: 10,
        isActive: true,
      },
      {
        key: 'workouts_50',
        category: 'workout' as const,
        title: 'Полтинник',
        description: 'Завершите 50 тренировок',
        icon: '🔥',
        color: 'orange',
        requirementType: 'total_workouts',
        requirementValue: 50,
        isActive: true,
      },
      {
        key: 'workouts_100',
        category: 'workout' as const,
        title: 'Сотня тренировок',
        description: 'Завершите 100 тренировок',
        icon: '🏅',
        color: 'yellow',
        requirementType: 'total_workouts',
        requirementValue: 100,
        isActive: true,
      },
      {
        key: 'workouts_500',
        category: 'workout' as const,
        title: 'Легенда',
        description: 'Завершите 500 тренировок',
        icon: '👑',
        color: 'purple',
        requirementType: 'total_workouts',
        requirementValue: 500,
        isActive: true,
      },
      // Использование функционала
      {
        key: 'first_ai_chat',
        category: 'usage' as const,
        title: 'Первый диалог с ИИ',
        description: 'Отправьте первое сообщение AI-помощнику',
        icon: '🤖',
        color: 'emerald',
        requirementType: 'ai_chat_messages',
        requirementValue: 1,
        isActive: true,
      },
      {
        key: 'ai_chats_10',
        category: 'usage' as const,
        title: 'AI Собеседник',
        description: 'Отправьте 10 сообщений AI-помощнику',
        icon: '💬',
        color: 'blue',
        requirementType: 'ai_chat_messages',
        requirementValue: 10,
        isActive: true,
      },
      {
        key: 'ai_chats_50',
        category: 'usage' as const,
        title: 'AI Эксперт',
        description: 'Отправьте 50 сообщений AI-помощнику',
        icon: '🧠',
        color: 'purple',
        requirementType: 'ai_chat_messages',
        requirementValue: 50,
        isActive: true,
      },
      // Социальные
      {
        key: 'find_trainer',
        category: 'social' as const,
        title: 'Найди своего тренера',
        description: 'Присоединитесь к персональному тренеру',
        icon: '🤝',
        color: 'emerald',
        requirementType: 'trainers_connected',
        requirementValue: 1,
        isActive: true,
      },
      {
        key: 'first_group_join',
        category: 'social' as const,
        title: 'В команде!',
        description: 'Вступите в первую группу тренера',
        icon: '👥',
        color: 'cyan',
        requirementType: 'groups_joined',
        requirementValue: 1,
        isActive: true,
      },
      {
        key: 'first_trainer_message',
        category: 'social' as const,
        title: 'Первый контакт',
        description: 'Напишите сообщение тренеру впервые',
        icon: '📩',
        color: 'indigo',
        requirementType: 'trainer_messages',
        requirementValue: 1,
        isActive: true,
      },
      {
        key: 'trainer_messages_50',
        category: 'social' as const,
        title: 'Активный общник',
        description: 'Отправьте 50 сообщений тренеру',
        icon: '🗣️',
        color: 'pink',
        requirementType: 'trainer_messages',
        requirementValue: 50,
        isActive: true,
      },
      // Прогресс (personal records + progression coeff)
      {
        key: 'first_pr',
        category: 'progress' as const,
        title: 'Личный рекорд!',
        description: 'Установите первый личный рекорд',
        icon: '🎯',
        color: 'emerald',
        requirementType: 'personal_records',
        requirementValue: 1,
        isActive: true,
      },
      {
        key: 'pr_5',
        category: 'progress' as const,
        title: 'Пять рекордов',
        description: 'Установите 5 личных рекордов',
        icon: '🏅',
        color: 'blue',
        requirementType: 'personal_records',
        requirementValue: 5,
        isActive: true,
      },
      {
        key: 'pr_25',
        category: 'progress' as const,
        title: 'Машина прогресса',
        description: 'Установите 25 личных рекордов',
        icon: '🚀',
        color: 'purple',
        requirementType: 'personal_records',
        requirementValue: 25,
        isActive: true,
      },
      {
        key: 'progress_10pct',
        category: 'progress' as const,
        title: 'Рост силы',
        description: 'Покажите средний прогресс +10% за месяц',
        icon: '📈',
        color: 'orange',
        requirementType: 'progression_coeff',
        requirementValue: 10,
        isActive: true,
      },
      {
        key: 'progress_25pct',
        category: 'progress' as const,
        title: 'Взрывной прогресс',
        description: 'Покажите средний прогресс +25% за месяц',
        icon: '⚡',
        color: 'yellow',
        requirementType: 'progression_coeff',
        requirementValue: 25,
        isActive: true,
      },
    ]

    await Achievement.updateOrCreateMany('key', achievements)
  }
}
