import { BaseSeeder } from '@adonisjs/lucid/seeders';
import Exercise from '#models/exercise';

export default class ExerciseSeeder extends BaseSeeder {
  static environment: string[] = ['development', 'production'];
  public async run() {
    await Exercise.updateOrCreateMany('id', [
      // ========================================
      // STRENGTH (КАЧАЛКА) - ГРУДЬ
      // ========================================
      {
        id: 'bench_press',
        title: 'Жим лежа',
        category: 'strength',
        keywords: ['жим', 'жим лежа', 'bench', 'bench press'],
        zones: ['chests', 'triceps', 'shoulders'],
        intensity: 0.8,
      },
      {
        id: 'incline_bench_press',
        title: 'Жим на наклонной',
        category: 'strength',
        keywords: ['жим наклонной', 'наклонный жим', 'incline', 'incline bench'],
        zones: ['chests', 'shoulders', 'triceps'],
        intensity: 0.75,
      },
      {
        id: 'dumbbell_fly',
        title: 'Разводка гантелей',
        category: 'strength',
        keywords: ['разводка', 'разводки', 'fly', 'dumbbell fly'],
        zones: ['chests'],
        intensity: 0.6,
      },
      {
        id: 'cable_crossover',
        title: 'Кроссовер',
        category: 'strength',
        keywords: ['кроссовер', 'crossover', 'cable'],
        zones: ['chests'],
        intensity: 0.65,
      },
      {
        id: 'hammer_press',
        title: 'Жим в хаммере',
        category: 'strength',
        keywords: ['хаммер', 'hammer', 'hammer press'],
        zones: ['chests', 'triceps', 'shoulders'],
        intensity: 0.75,
      },

      // ========================================
      // STRENGTH - СПИНА
      // ========================================
      {
        id: 'barbell_row',
        title: 'Тяга штанги в наклоне',
        category: 'strength',
        keywords: ['тяга штанги', 'тяга в наклоне', 'barbell row', 'bent over row'],
        zones: ['back', 'biceps', 'core'],
        intensity: 0.8,
      },
      {
        id: 'dumbbell_row',
        title: 'Тяга гантели',
        category: 'strength',
        keywords: ['тяга гантели', 'тяга одной', 'dumbbell row', 'one arm row'],
        zones: ['back', 'biceps'],
        intensity: 0.75,
      },
      {
        id: 'lat_pulldown',
        title: 'Тяга верхнего блока',
        category: 'strength',
        keywords: ['верхний блок', 'тяга сверху', 'lat pulldown', 'pulldown'],
        zones: ['back', 'biceps'],
        intensity: 0.7,
      },
      {
        id: 'seated_row',
        title: 'Тяга к поясу',
        category: 'strength',
        keywords: ['тяга к поясу', 'горизонтальная тяга', 'seated row', 'cable row'],
        zones: ['back', 'biceps'],
        intensity: 0.75,
      },
      {
        id: 'pullover',
        title: 'Пуловер',
        category: 'strength',
        keywords: ['пуловер', 'pullover'],
        zones: ['back', 'chests'],
        intensity: 0.65,
      },
      {
        id: 'hyperextension',
        title: 'Гиперэкстензия',
        category: 'strength',
        keywords: ['гиперэкстензия', 'гипер', 'hyperextension'],
        zones: ['back', 'glutes'],
        intensity: 0.6,
      },
      {
        id: 'deadlift',
        title: 'Становая тяга',
        category: 'strength',
        keywords: ['становая', 'тяга', 'deadlift'],
        zones: ['back', 'legs', 'glutes', 'core'],
        intensity: 0.9,
      },
      {
        id: 'romanian_deadlift',
        title: 'Румынская тяга',
        category: 'strength',
        keywords: ['румынская', 'румынка', 'romanian', 'rdl'],
        zones: ['back', 'glutes', 'legs'],
        intensity: 0.75,
      },

      // ========================================
      // STRENGTH - ПЛЕЧИ
      // ========================================
      {
        id: 'overhead_press',
        title: 'Жим стоя',
        category: 'strength',
        keywords: ['жим стоя', 'армейский', 'overhead', 'press', 'strict press', 'military press'],
        zones: ['shoulders', 'triceps', 'core'],
        intensity: 0.8,
      },
      {
        id: 'lateral_raise',
        title: 'Махи в стороны',
        category: 'strength',
        keywords: ['махи в стороны', 'махи гантелей', 'lateral raise', 'side raise'],
        zones: ['shoulders'],
        intensity: 0.6,
      },
      {
        id: 'bent_over_raise',
        title: 'Махи в наклоне',
        category: 'strength',
        keywords: ['махи в наклоне', 'разводка в наклоне', 'bent over raise', 'rear delt'],
        zones: ['shoulders', 'back'],
        intensity: 0.6,
      },
      {
        id: 'front_raise',
        title: 'Махи вперед',
        category: 'strength',
        keywords: ['махи вперед', 'подъем вперед', 'front raise'],
        zones: ['shoulders'],
        intensity: 0.6,
      },
      {
        id: 'upright_row',
        title: 'Протяжка',
        category: 'strength',
        keywords: ['протяжка', 'тяга к подбородку', 'upright row'],
        zones: ['shoulders', 'back'],
        intensity: 0.7,
      },
      {
        id: 'reverse_fly',
        title: 'Обратные разведения',
        category: 'strength',
        keywords: ['обратные разведения', 'обратная разводка', 'reverse fly', 'pec deck'],
        zones: ['shoulders', 'back'],
        intensity: 0.65,
      },

      // ========================================
      // STRENGTH - РУКИ (БИЦЕПС)
      // ========================================
      {
        id: 'barbell_curl',
        title: 'Подъем на бицепс (штанга)',
        category: 'strength',
        keywords: ['бицепс штанга', 'подъем штанги', 'barbell curl', 'curl'],
        zones: ['biceps'],
        intensity: 0.7,
      },
      {
        id: 'dumbbell_curl',
        title: 'Подъем на бицепс (гантели)',
        category: 'strength',
        keywords: ['бицепс гантели', 'подъем гантелей', 'dumbbell curl'],
        zones: ['biceps'],
        intensity: 0.7,
      },
      {
        id: 'hammer_curl',
        title: 'Молоток',
        category: 'strength',
        keywords: ['молоток', 'молотки', 'hammer', 'hammer curl'],
        zones: ['biceps', 'forearms'],
        intensity: 0.65,
      },
      {
        id: 'preacher_curl',
        title: 'Скамья Скотта',
        category: 'strength',
        keywords: ['скотт', 'скамья скотта', 'preacher', 'preacher curl'],
        zones: ['biceps'],
        intensity: 0.7,
      },

      // ========================================
      // STRENGTH - РУКИ (ТРИЦЕПС)
      // ========================================
      {
        id: 'skull_crusher',
        title: 'Французский жим',
        category: 'strength',
        keywords: ['французский', 'французский жим', 'skull crusher'],
        zones: ['triceps'],
        intensity: 0.75,
      },
      {
        id: 'tricep_pushdown',
        title: 'Разгибания на блоке',
        category: 'strength',
        keywords: ['разгибания', 'блок трицепс', 'pushdown', 'tricep pushdown'],
        zones: ['triceps'],
        intensity: 0.65,
      },
      {
        id: 'dip',
        title: 'Отжимания на брусьях',
        category: 'strength',
        keywords: ['брусья', 'dip', 'dips'],
        zones: ['triceps', 'chests', 'shoulders'],
        intensity: 0.8,
      },
      {
        id: 'close_grip_bench',
        title: 'Жим узким хватом',
        category: 'strength',
        keywords: ['узкий хват', 'узкий жим', 'close grip'],
        zones: ['triceps', 'chests'],
        intensity: 0.75,
      },

      // ========================================
      // STRENGTH - НОГИ
      // ========================================
      {
        id: 'squat',
        title: 'Присед',
        category: 'strength',
        keywords: ['присед', 'приседания', 'squat', 'back squat'],
        zones: ['legs', 'glutes', 'core'],
        intensity: 0.85,
      },
      {
        id: 'front_squat',
        title: 'Фронтальный присед',
        category: 'strength',
        keywords: ['фронтальный', 'front squat'],
        zones: ['legs', 'glutes', 'core', 'shoulders'],
        intensity: 0.9,
      },
      {
        id: 'leg_press',
        title: 'Жим ногами',
        category: 'strength',
        keywords: ['жим ногами', 'leg press'],
        zones: ['legs', 'glutes'],
        intensity: 0.8,
      },
      {
        id: 'leg_extension',
        title: 'Разгибания ног',
        category: 'strength',
        keywords: ['разгибания ног', 'квадрицепс', 'leg extension'],
        zones: ['legs'],
        intensity: 0.65,
      },
      {
        id: 'leg_curl',
        title: 'Сгибания ног',
        category: 'strength',
        keywords: ['сгибания ног', 'бицепс бедра', 'leg curl'],
        zones: ['legs'],
        intensity: 0.65,
      },
      {
        id: 'lunge',
        title: 'Выпады',
        category: 'strength',
        keywords: ['выпады', 'lunge', 'lunges'],
        zones: ['legs', 'glutes'],
        intensity: 0.7,
      },
      {
        id: 'bulgarian_split_squat',
        title: 'Болгарские выпады',
        category: 'strength',
        keywords: ['болгарские', 'bulgarian', 'split squat'],
        zones: ['legs', 'glutes'],
        intensity: 0.75,
      },
      {
        id: 'calf_raise',
        title: 'Икры стоя',
        category: 'strength',
        keywords: ['икры', 'икры стоя', 'calf raise'],
        zones: ['legs'],
        intensity: 0.6,
      },
      {
        id: 'seated_calf_raise',
        title: 'Икры сидя',
        category: 'strength',
        keywords: ['икры сидя', 'seated calf'],
        zones: ['legs'],
        intensity: 0.6,
      },

      // ========================================
      // STRENGTH - ПРЕСС
      // ========================================
      {
        id: 'crunch',
        title: 'Скручивания',
        category: 'strength',
        keywords: ['скручивания', 'crunch'],
        zones: ['core'],
        intensity: 0.5,
      },
      {
        id: 'leg_raise',
        title: 'Подъемы ног',
        category: 'strength',
        keywords: ['подъемы ног', 'leg raise'],
        zones: ['core'],
        intensity: 0.6,
      },
      {
        id: 'bicycle_crunch',
        title: 'Велосипед',
        category: 'strength',
        keywords: ['велосипед', 'bicycle'],
        zones: ['core'],
        intensity: 0.55,
      },
      {
        id: 'russian_twist',
        title: 'Русский твист',
        category: 'strength',
        keywords: ['русский твист', 'russian twist'],
        zones: ['core'],
        intensity: 0.6,
      },
      {
        id: 'plank',
        title: 'Планка',
        category: 'strength',
        keywords: ['планка', 'plank'],
        zones: ['core', 'shoulders'],
        intensity: 0.6,
      },
      {
        id: 'ab_wheel',
        title: 'Ролик для пресса',
        category: 'strength',
        keywords: ['ролик', 'ab wheel', 'колесо'],
        zones: ['core', 'shoulders'],
        intensity: 0.75,
      },

      // ========================================
      // OLYMPIC (ОЛИМПИЙСКАЯ ТЯЖЕЛАЯ АТЛЕТИКА)
      // ========================================
      {
        id: 'snatch',
        title: 'Рывок',
        category: 'olympic',
        keywords: ['рывок', 'snatch'],
        zones: ['shoulders', 'back', 'legs', 'core'],
        intensity: 0.95,
      },
      {
        id: 'clean',
        title: 'Взятие на грудь',
        category: 'olympic',
        keywords: ['взятие', 'clean', 'power clean'],
        zones: ['back', 'legs', 'shoulders', 'core'],
        intensity: 0.9,
      },
      {
        id: 'clean_and_jerk',
        title: 'Толчок',
        category: 'olympic',
        keywords: ['толчок', 'clean and jerk', 'jerk'],
        zones: ['shoulders', 'legs', 'back', 'core'],
        intensity: 0.95,
      },
      {
        id: 'push_press',
        title: 'Швунг жимовой',
        category: 'olympic',
        keywords: ['швунг', 'push press'],
        zones: ['shoulders', 'legs', 'core'],
        intensity: 0.85,
      },
      {
        id: 'push_jerk',
        title: 'Швунг толчковый',
        category: 'olympic',
        keywords: ['швунг толчковый', 'push jerk'],
        zones: ['shoulders', 'legs', 'core'],
        intensity: 0.9,
      },
      {
        id: 'overhead_squat',
        title: 'Оверхед присед',
        category: 'olympic',
        keywords: ['оверхед', 'overhead squat', 'ohs'],
        zones: ['legs', 'shoulders', 'core'],
        intensity: 0.9,
      },

      // ========================================
      // GYMNASTICS (ГИМНАСТИКА)
      // ========================================
      {
        id: 'pull_up',
        title: 'Подтягивания',
        category: 'gymnastics',
        keywords: ['подтягивания', 'pull up', 'pull-up'],
        zones: ['back', 'biceps', 'core'],
        intensity: 0.8,
      },
      {
        id: 'chest_to_bar',
        title: 'Подтягивания до груди',
        category: 'gymnastics',
        keywords: ['до груди', 'chest to bar', 'c2b'],
        zones: ['back', 'biceps', 'core'],
        intensity: 0.85,
      },
      {
        id: 'push_up',
        title: 'Отжимания',
        category: 'gymnastics',
        keywords: ['отжимания', 'push up', 'push-up'],
        zones: ['chests', 'triceps', 'shoulders', 'core'],
        intensity: 0.6,
      },
      {
        id: 'handstand_push_up',
        title: 'Отжимания в стойке',
        category: 'gymnastics',
        keywords: ['стойка', 'hspu', 'handstand'],
        zones: ['shoulders', 'triceps', 'core'],
        intensity: 0.9,
      },
      {
        id: 'muscle_up',
        title: 'Выход силой',
        category: 'gymnastics',
        keywords: ['выход', 'muscle up', 'muscle-up'],
        zones: ['back', 'shoulders', 'triceps', 'core'],
        intensity: 0.95,
      },
      {
        id: 'rope_climb',
        title: 'Лазание по канату',
        category: 'gymnastics',
        keywords: ['канат', 'rope', 'rope climb'],
        zones: ['back', 'biceps', 'core', 'forearms'],
        intensity: 0.9,
      },
      {
        id: 'toes_to_bar',
        title: 'Носки к перекладине',
        category: 'gymnastics',
        keywords: ['носки', 'ttb', 'toes to bar'],
        zones: ['core', 'shoulders'],
        intensity: 0.75,
      },
      {
        id: 'knees_to_elbow',
        title: 'Колени к локтям',
        category: 'gymnastics',
        keywords: ['колени', 'k2e', 'knees to elbow'],
        zones: ['core', 'shoulders'],
        intensity: 0.7,
      },
      {
        id: 'sit_up',
        title: 'Ситапы',
        category: 'gymnastics',
        keywords: ['ситап', 'sit up', 'sit-up'],
        zones: ['core'],
        intensity: 0.5,
      },
      {
        id: 'l_sit',
        title: 'Уголок',
        category: 'gymnastics',
        keywords: ['уголок', 'l sit', 'l-sit'],
        zones: ['core', 'shoulders'],
        intensity: 0.8,
      },

      // ========================================
      // FUNCTIONAL (ФУНКЦИОНАЛЬНЫЕ)
      // ========================================
      {
        id: 'burpee',
        title: 'Берпи',
        category: 'functional',
        keywords: ['берпи', 'burpee', 'burpees'],
        zones: ['legs', 'core', 'shoulders', 'chests'],
        intensity: 0.9,
      },
      {
        id: 'thruster',
        title: 'Трастер',
        category: 'functional',
        keywords: ['трастер', 'thruster'],
        zones: ['legs', 'shoulders', 'core'],
        intensity: 0.9,
      },
      {
        id: 'wall_ball',
        title: 'Броски мяча в стену',
        category: 'functional',
        keywords: ['мяч', 'wall ball', 'wallball'],
        zones: ['legs', 'shoulders', 'core'],
        intensity: 0.75,
      },
      {
        id: 'box_jump',
        title: 'Запрыгивания на тумбу',
        category: 'functional',
        keywords: ['тумба', 'запрыгивания', 'box jump', 'box'],
        zones: ['legs', 'glutes'],
        intensity: 0.8,
      },
      {
        id: 'kettlebell_swing',
        title: 'Махи гирей',
        category: 'functional',
        keywords: ['махи', 'гиря', 'swing', 'kettlebell'],
        zones: ['glutes', 'back', 'shoulders', 'core'],
        intensity: 0.8,
      },
      {
        id: 'dumbbell_snatch',
        title: 'Рывок гантели',
        category: 'functional',
        keywords: ['рывок гантели', 'гантель', 'dumbbell snatch'],
        zones: ['shoulders', 'back', 'legs', 'core'],
        intensity: 0.85,
      },
      {
        id: 'dumbbell_clean',
        title: 'Взятие гантели',
        category: 'functional',
        keywords: ['взятие гантели', 'dumbbell clean'],
        zones: ['shoulders', 'back', 'legs'],
        intensity: 0.8,
      },
      {
        id: 'farmers_walk',
        title: 'Прогулка фермера',
        category: 'functional',
        keywords: ['фермер', 'farmer', 'farmers walk'],
        zones: ['forearms', 'shoulders', 'core', 'legs'],
        intensity: 0.75,
      },
      {
        id: 'sled_push',
        title: 'Толкание санок',
        category: 'functional',
        keywords: ['санки', 'sled', 'sled push'],
        zones: ['legs', 'shoulders', 'core'],
        intensity: 0.85,
      },
      {
        id: 'tire_flip',
        title: 'Переворачивание покрышки',
        category: 'functional',
        keywords: ['покрышка', 'tire', 'tire flip'],
        zones: ['back', 'legs', 'glutes', 'shoulders'],
        intensity: 0.9,
      },

      // ========================================
      // CARDIO (КАРДИО)
      // ========================================
      {
        id: 'run',
        title: 'Бег',
        category: 'cardio',
        keywords: ['бег', 'run', 'running'],
        zones: ['legs', 'core'],
        intensity: 0.6,
      },
      {
        id: 'rowing',
        title: 'Гребля',
        category: 'cardio',
        keywords: ['гребля', 'row', 'rowing'],
        zones: ['back', 'legs', 'core', 'shoulders'],
        intensity: 0.75,
      },
      {
        id: 'assault_bike',
        title: 'Assault Bike',
        category: 'cardio',
        keywords: ['байк', 'bike', 'assault', 'air bike'],
        zones: ['legs', 'shoulders', 'core'],
        intensity: 0.8,
      },
      {
        id: 'shuttle_run',
        title: 'Челночный бег',
        category: 'cardio',
        keywords: ['челнок', 'челночный', 'shuttle'],
        zones: ['legs', 'core'],
        intensity: 0.75,
      },
      {
        id: 'double_under',
        title: 'Двойные прыжки',
        category: 'cardio',
        keywords: ['двойные', 'скакалка', 'double under', 'du'],
        zones: ['legs', 'shoulders', 'core'],
        intensity: 0.7,
      },
      {
        id: 'single_under',
        title: 'Одинарные прыжки',
        category: 'cardio',
        keywords: ['одинарные', 'скакалка одинарная', 'single under', 'su'],
        zones: ['legs', 'shoulders'],
        intensity: 0.5,
      },
      {
        id: 'ski_erg',
        title: 'Лыжный эрг',
        category: 'cardio',
        keywords: ['лыжи', 'ski', 'ski erg'],
        zones: ['back', 'shoulders', 'core', 'legs'],
        intensity: 0.75,
      },
    ]);
  }
}
